#+TITLE: Informatica @ SEFA 2018/2019 - Esame

* Modalità di esame

  Le  date degli  appelli sono  ancora da  decidere. Le  date per  gli
  appelli successivi ai primi due sono ancora provvisorie.

  - Primo appello scritto: 14/1/2019 - 9.00-14.00 - Aula 2 CU002
  - Secondo appello scritto: 11/2/2019 - 9.00-14.00 - Aula 2 CU002
  - Terzo appello scritto:  3/6/2019 - 9.00-14.00 - Aula 2 CU002
  - Quarto appello scritto: 1/7/2019 - 9.00-14.00 - Aula 2 CU002
  - Quinto appello scritto: 9/9/2019 - 9.00-14.00 - Aula 2 CU002

  Le   modalità  di   esame  saranno   precisate  durante   il  corso.
  Quanto  scritto  qui  è  indicativo  di quello  che  è  stato  fatto
  l'anno scorso.

  - prova scritta in aula
  - esercizio di programmazione
  - esame orale.

  *Non ci sono esoneri*

  L'esame  orale  sarà  principalmente  una  discussione  della  prova
  scritta  con qualche  domanda integrativa,  più la  correzione degli
  esercizi di programmazione.
  
  Lo  studente  dovrà  portare,   per  accedere  all'esame  orale,  un
  esercizio di  programmazione Python/SQL  che sarà testato  con degli
  input  segreti. Per  facilitare lo  svolgimento dell'esercizio  sono
  inclusi dei test  preliminari che verificare che  le soluzioni siano
  bene impostate.


  - Testo dell'esercizio: [[file:docs/esercizio2018.pdf][esercizio2018.pdf]] 
  - Test preliminari: saranno disponibili a breve.
  
