#+TITLE: Informatica, 2017 @ SEFA - Homework

#+macro: subject_prefix =[INFOSEFA2017HW]=
#+macro: email_address  =massimo.lauria@uniroma1.it=

* Come consegnare gli esercizi

  Gli studenti consegnano i propri  compiti via email, che poi vengono
  gestiti da  un software.  Questo software  è molto  primitivo perché
  l'ho  improvvisato   nelle  due   settimane  precedenti   al  corso.
  *Fatemi sapere*  se ci  sono dei  problemi tecnici.  Perché un'email
  venga vista dal software 

  - deve avere {{{subject_prefix}}} all'inizio dell'oggetto, ad esempio
    
    *Oggetto:* {{{subject_prefix}}} =consegna del primo esercizio=
 
  - deve essere inviata all'indirizzo {{{email_address}}}.
    
  *Mi  raccomando*: se  una  delle due  condizioni  sopra non  dovesse
  essere  rispettata  i  vostri messaggi  potrebbero  essere  perduti,
  dimenticati o ignorati.

  Il software accetta tre tipi di email.

  1. Iscrizione  al sistema. Deve essere  fatta una sola volta,  e non
     sarà possibile  consegnare finché non viene  effettuata, inviando
     un messaggio con i propri dati, nella forma

     #+begin_example
     iscrizione
  
     nome : <NOME> 
     cognome : <COGNOME>
     matricola: <NUMERO DI MATRICOLA>
  
     #+end_example

     Successivamente all  registrazione tutti i messaggi  che arrivano
     dallo  stesso indirizzo  di posta  elettronica vengono  associati
     allo studente indicato.

  2. Consegna. Ad  ogni compito  corrisponde un  codice alfanumerico.
     La soluzione  del compito deve  essere inviata come  (unico) file
     allegato ad un messaggio della forma
 
     #+begin_example
     consegna
  
     homework : <CODICE>
  
     #+end_example

  3. Situazione. Lo studente può chiedere di conoscere lo stato dei
     suoi esercizi con un messaggio della forma
     
     #+begin_example
     situazione
     #+end_example
  
* Formato dei messaggi 

  I messaggi  per la  consegna dei compiti  deveono essere  scritti in
  testo  semplice non  formattato (=text/plain=).  Molti programmi  di
  posta  elettronica   mandano  messaggi  in  HTML.   Questi  verranno
  ignorati.  Altri programmi  di  posta mandano  messaggi  in HTML  ma
  inviato contestualmente  una versione in  testo semplice che  ha più
  o  meno gli  stessi  contenuti.  Se la  versione  in testo  semplice
  rispetta le specifiche allora non c'è problema.

  Lo studente è responsabile delle email che invia e deve farsi carico
  di  controllare che  i messaggi  soddisfino i  requisiti di  formato
  necessari.  In caso  contrario  i messaggi  (ed  i relativi  compiti
  consegnati) potrebbero andare persi o potrebbero essere ignorati.

  *Controllate la configurazione del vostro programma di posta elettronica.*
