#+TITLE: Informatica @ SEFA 2018/2019 - Diario delle lezioni

Qui potete trovare  tutte le informazioni riguardo  il contenuto delle
lezioni,  ed il  relativo  materiale. Tenete  d'occhio questa  pagina.

* <2018-10-03 mer> Lezione 5 - Elementi del linguaggio python

  Vediamo come  usare Python  come una  calcolatrice e  per manipolare
  i  tipi numerici  più semplici.  Poi vediamo  l'uso delle  variabili
  e l'uso delle stringhe.

  Slide: ([[file:docs/lecture05-slides.pdf][schermo]]|[[file:docs/lecture05-print.pdf][stampa]])
  
  Letture: Cap 3. Libro di python

* <2018-10-01 Mon> Lezione 4 - Tutorial del terminale

  Abbiamo visto come muoverci tra i file del computer usando i comandi
  del  terminale. Contestualmente  abbiamo  cercato di  far girare  il
  nostro   primo  esempio   di   codice  python   dalle  slide   della
  lezione scorsa.

  Tutorial (file rivisitato della Lezione 1): ([[file:docs/lecture01b-slides.pdf][schermo]]|[[file:docs/lecture01b-print.pdf][stampa]])
  
  Questionario: [[http://bit.ly/INFO2018-04a][bit.ly/INFO2018-04a]]

* <2018-09-28 Fri> Lezione 3 - Programmi

  Abbiamo descritto a  grandi linee come opera una CPU  nel modello di
  von  Neumann.  Abbiamo  quindi   visto  come  sia  importante  avere
  linguaggi  di  alto  livello.  Questi  permattono  "astrazioni"  più
  potenti.   L'astrazione  è   un   concetto   che  abbiamo   definito
  contestualmente.  Abbiamo  descritto  la  differenza  tra  linguaggi
  compilati  e   interpretati,  così   come  tra  linguaggi   di  alto
  e basso livello. Abbiamo introdotto brevemente Python e SQL, e detto
  cosa sono variabili e funzioni in contesto di Python.
  
  Questionari:
  - Rappresentazione dei dati: [[https://bit.ly/INFO2018-02d][bit.ly/INFO2018-02d]]
  - Programmazione e Astrazione http://bit.ly/INFO2018-03a
  
  Slide: ([[file:docs/lecture03-slides.pdf][schermo]]|[[file:docs/lecture03-print.pdf][stampa]])

* <2018-09-26 Wed> Lezione 2 - Dati e programmi

  Abbiamo accennato  ad alcuni elementi della  storia dei calcolatori,
  da Babbage a  Turing passando per von Neumann.  Dopodiché la lezione
  si  è concentrata  prima  sulla  codifica di  dati,  ovvero di  come
  vengano codificati numeri  interi in binario e  esadecimale, e testi
  in  ASCII, ASCII  esteso, e  UTF-8.  Sono stati  fatti anche  esempi
  riguardanti la codifica di immagini e segnali.
   
  Questionari:
  - Feedback logistico [[https://bit.ly/INFO2018-02a][bit.ly/INFO2018-02a]]
  - Storia e architettura dei calcolatori: [[https://bit.ly/INFO2018-02c][bit.ly/INFO2018-02c]]
  
  Slide: ([[file:docs/lecture02-slides.pdf][schermo]]|[[file:docs/lecture02-print.pdf][stampa]])

  Letture: Cap 1. Libro di python
 
* <2018-09-24 Mon> Lezione 1 - Introduzione

  Abbiamo introdotto il corso,  fornendo le informazioni logistiche di
  base. Poi abbiamo visto come  effettuare i primi passi nell'ambiente
  linux  del  laboratorio: come  trovare  i  programmi necessari  allo
  svolgimento delle esercitazioni e come utilizzare il terminale.
   
  Questionario: [[https://bit.ly/INFO2018-01][bit.ly/INFO2018-01]]
  
  Slide: ([[file:docs/lecture01-slides.pdf][schermo]]|[[file:docs/lecture01-print.pdf][stampa]])
  
  Tutorial: ([[file:docs/lecture01b-slides.pdf][schermo]]|[[file:docs/lecture01b-print.pdf][stampa]])

  Letture: Cap 1. Libro di python
