<!-- -*- mode: html -*- -->
<header>
  <nav>
    <ul id="nav">
      <li class="left" style="font-variant: small-caps">
        <a id="homelink" href="index.html">
          Informatica, 2017 @ SEFA
          </a>
      </li>
      <div class="right">
        <li class="left"> <a href="journal.html">Lezioni</a></li>
        <li class="left"> <a href="homework.html">Homework</a></li>
      </div>
    </ul>
  </nav>
</header>

<script type="text/javascript">highlightCurrentPage()</script>
